// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUTsEInZaTfj06o9RYo8cn1DyoZMj5jFc',
    appId: '1:899679010074:web:80d6fbf3a8354f5521c0a3',
    messagingSenderId: '899679010074',
    projectId: 'db-bibliodac',
    authDomain: 'db-bibliodac.firebaseapp.com',
    storageBucket: 'db-bibliodac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGSOW63o8OOPjhU15Z7RQBZIkT1p8AR4w',
    appId: '1:899679010074:android:91318ff2510af83721c0a3',
    messagingSenderId: '899679010074',
    projectId: 'db-bibliodac',
    storageBucket: 'db-bibliodac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMUUASZDmir3S7u_OheEgojTOSkGcn73o',
    appId: '1:899679010074:ios:0ae40aec03fa2ae621c0a3',
    messagingSenderId: '899679010074',
    projectId: 'db-bibliodac',
    storageBucket: 'db-bibliodac.appspot.com',
    iosBundleId: 'com.example.proyectobibliodac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMUUASZDmir3S7u_OheEgojTOSkGcn73o',
    appId: '1:899679010074:ios:0ae40aec03fa2ae621c0a3',
    messagingSenderId: '899679010074',
    projectId: 'db-bibliodac',
    storageBucket: 'db-bibliodac.appspot.com',
    iosBundleId: 'com.example.proyectobibliodac',
  );
}
